// <auto-generated />
using AmlakState.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arch.Migrations
{
    [DbContext(typeof(ArchDbContext))]
    [Migration("20250904142334_ft")]
    partial class ft
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AmlakState.Models.AgriculturalHolding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("ActualArea")
                        .HasColumnType("float");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Association")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BuildingsCount")
                        .HasColumnType("int");

                    b.Property<string>("DataResourses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EasternBorder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Houd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HyazaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MarkazId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NorthernBorder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("RegistedArea")
                        .HasColumnType("float");

                    b.Property<int?>("SourceOfOwnershipId")
                        .HasColumnType("int");

                    b.Property<string>("SouthernBorder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WesternBorder")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MarkazId");

                    b.HasIndex("SourceOfOwnershipId");

                    b.ToTable("AgriculturalHoldings");
                });

            modelBuilder.Entity("AmlakState.Models.Markaz", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Markazes");
                });

            modelBuilder.Entity("AmlakState.Models.PropertyCoordinate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AgriculturalHoldingId")
                        .HasColumnType("int");

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("AgriculturalHoldingId");

                    b.ToTable("PropertyCoordinates");
                });

            modelBuilder.Entity("Arch.Models.Attachments", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AgriculturalHoldingId")
                        .HasColumnType("int");

                    b.Property<string>("Attachment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AgriculturalHoldingId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("Arch.Models.Madina_Maglas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("MarkazId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MarkazId");

                    b.ToTable("Madina_Maglas");
                });

            modelBuilder.Entity("Arch.Models.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Arch.Models.SourceOfOwnership", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SourceOfOwnership");
                });

            modelBuilder.Entity("Arch.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<int?>("MarkazId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserRoleId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MarkazId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("AmlakState.Models.AgriculturalHolding", b =>
                {
                    b.HasOne("AmlakState.Models.Markaz", "Markaz")
                        .WithMany("AgriculturalHoldings")
                        .HasForeignKey("MarkazId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arch.Models.SourceOfOwnership", "SourceOfOwnership")
                        .WithMany("AgriculturalHoldings")
                        .HasForeignKey("SourceOfOwnershipId");

                    b.Navigation("Markaz");

                    b.Navigation("SourceOfOwnership");
                });

            modelBuilder.Entity("AmlakState.Models.PropertyCoordinate", b =>
                {
                    b.HasOne("AmlakState.Models.AgriculturalHolding", "AgriculturalHolding")
                        .WithMany("PropertyCoordinates")
                        .HasForeignKey("AgriculturalHoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgriculturalHolding");
                });

            modelBuilder.Entity("Arch.Models.Attachments", b =>
                {
                    b.HasOne("AmlakState.Models.AgriculturalHolding", "AgriculturalHolding")
                        .WithMany("Attachments")
                        .HasForeignKey("AgriculturalHoldingId");

                    b.Navigation("AgriculturalHolding");
                });

            modelBuilder.Entity("Arch.Models.Madina_Maglas", b =>
                {
                    b.HasOne("AmlakState.Models.Markaz", "Markaz")
                        .WithMany("MadinaMaglas")
                        .HasForeignKey("MarkazId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Markaz");
                });

            modelBuilder.Entity("Arch.Models.User", b =>
                {
                    b.HasOne("AmlakState.Models.Markaz", "Markaz")
                        .WithMany()
                        .HasForeignKey("MarkazId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Arch.Models.Role", "UserRole")
                        .WithMany("User")
                        .HasForeignKey("UserRoleId");

                    b.Navigation("Markaz");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("AmlakState.Models.AgriculturalHolding", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("PropertyCoordinates");
                });

            modelBuilder.Entity("AmlakState.Models.Markaz", b =>
                {
                    b.Navigation("AgriculturalHoldings");

                    b.Navigation("MadinaMaglas");
                });

            modelBuilder.Entity("Arch.Models.Role", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Arch.Models.SourceOfOwnership", b =>
                {
                    b.Navigation("AgriculturalHoldings");
                });
#pragma warning restore 612, 618
        }
    }
}
